### PR TITLE
Add ES2015 support

### PR DESCRIPTION
**Pull request by stefanbuck**
### This PR is work in progress

I just wanted to create this PR to make progress on #106 and discuss it with you.

Here's what I did so far:
- Updated `grunt-contrib-jshint` to support ES6 syntax
- Added es2015 source files `app/babel/`
- ~~Added`grunt-browserify` and `grunt-babelify`~~ `grunt-babel`
- Added prompt: _Use es2015 (precompiled with Babel)_

~~The idea is that  `app/src` contains the ES2015 files. Browserify compiles these files to `app/scripts` and everything else works as usual.~~ Update: No module system for now now see https://github.com/yeoman/generator-chrome-extension/pull/117#issuecomment-136910041

**TODO:**
- [x] Add / update es2015 tests
- [x] Add / update es5 tests
- [x] Drop coffeescript support

### CODE REVIEW

**Comment by arthurvr** [comment]
Nice work! :+1: It would probably be easier if we'd directly drop Coffeescript support too.

**Comment by stefanbuck** [comment]
I tried to keep the changes as small as possible, but if @ragingwind is happy with dropping coffeescript I'm happy to cover it also in this PR.

**Comment by ragingwind** [comment]
@stefanbuck no problem. dropping coffeescript is also on the milestone

**Comment by stefanbuck** [comment]
I'm done. Please review it and leave some comments :wink:

**Comment by stefanbuck** [comment]
Because Babel just compiles es6 code into es5 without taking care of bundling the files together. By default Babel use commonJS which works nicely together with browserify. https://babeljs.io/docs/usage/modules/

**Comment by ragingwind** [comment]
I think, using browserify to use module system it would not be in this milestone. We could talk about that on the other issue. In my opinion, To support the module system, We also update the others of task, show how to use the module system on the source of the generated project. And I agree with the issue https://github.com/yeoman/generator-gulp-webapp/issues/32 . It's enough that using `grunt-babel' like this https://github.com/yeoman/generator-webapp/blob/afe7b0ef147db094ffa5ea915c535d859957ad99/app/templates/Gruntfile.js#L173

**Comment by stefanbuck** [comment]
Up to you @ragingwind :wink: I updated the files.

**Comment by stefanbuck** [comment]
I pushed a new commit 06961956b44856a9f9af6627c0107fc9091fe5a9 for the code review comments. Soon as you are happy with this PR, I will squash it down

**Comment by stefanbuck** [comment]
ahh sorry, I shouldn't write code before breakfast. Will fix it later :wink:

**Comment by stefanbuck** [comment]
@ragingwind comments are solved

**Comment by ragingwind** [comment]
LGTM, Could you squash it please? Thank a lot.

**Comment by ruyadorno** [comment]
oh, look at that, @stefanbuck being awesome again :confetti_ball:

**Comment by stefanbuck** [comment]
@ragingwind :shipit:

**Comment by ragingwind** [comment]
Thanks! Great

**Pull request merged**
