### PR TITLE
Replace grunt with gulp

### PR DESCRIPTION
**Pull request by ragingwind**
Yo, I think it's time to move to gulp. :) I was starting with `generator-gulp-webapp`. Here is some changes. PTAL @sindresorhus @addyosmani 

- Replace grunt with gulp
- babel is defaults for es6, gulpfile.babel.js
- Using gulp-sass(node-sass)
- Replace name of `debug` task to `watch`

### CODE REVIEW

**Comment by sindresorhus** [comment]
Generally looks good, but needs to be extensively manually tested. I would also drop Bower in favor of using npm for all dependencies (https://github.com/yeoman/yeoman/issues/1521).

**Comment by ragingwind** [comment]
I've tested manually with several types of extension. It's most likely that have no problem but I'll make a list of test cases for manual testing that can lead to develop an improvement including using npm3

**Comment by addyosmani** [comment]
LGTM echoing the same comments from Sindre about npm3 support. Is this something you wanted to tackle in this PR or separately?

**Comment by ragingwind** [comment]
@addyosmani I think, Separating is more clear and I'm not sure what should be changed for npm3 until now. I've been keep investing for improvement.

**Comment by ragingwind** [comment]
@addyosmani @sindresorhus I will merge and make a new PR for NPM3

**Comment by addyosmani** [comment]
:+1:

**Pull request merged**
