### PR TITLE
Document steps to adding Browserify

### PR DESCRIPTION
**Pull request by sungwoncho**
Added a recipe as discussed in https://github.com/yeoman/generator-chrome-extension/pull/153#issuecomment-217570985. Thanks @mashhoodr.

### CODE REVIEW

**Comment by ragingwind** [comment]
@sungwoncho Thanks. one more thing. Would you move the recipe file to under the `docs/recipes/`. and then rename the filename into just `browserify.md`. For example, https://github.com/yeoman/generator-webapp/tree/master/docs I would like to keep in same structure with other generators's docs

**Comment by sungwoncho** [comment]
@ragingwind That's reasonable. I made the changes.

**Comment by ragingwind** [comment]
Great, thanks

**Comment by emorling** [comment]
Any updated on how to use this with Chrome Manifest v3?

**Pull request merged**
