### PR TITLE
v0.7.1

### PR DESCRIPTION
**Pull request by UlisesGascon**
### Changelog
- https://github.com/yeoman/generator-chrome-extension/commit/664a679e4b2204fa007a5c6e0067f27de1b12c69 Set ESLint to parse ES6 if use Babel (#202) by @tuononh & @ragingwind
- https://github.com/yeoman/generator-chrome-extension/commit/9beabd23e71e6067259f2cc25215b26fd192aa7b Add plumber to babel task (#192) by @ragingwind 
- https://github.com/yeoman/generator-chrome-extension/commit/078af88d7f25fa093e69807aef93587fd394c717 Upgrade Travis to run using the lastest versions of Node (#206) by @RobertJGabriel
- https://github.com/yeoman/generator-chrome-extension/commit/35a512a6a4509e3e930243c37f17c4a7dcf47ad3  Support latest preset (ES-2015 - ES-2017) (#209) by @hqtoan94

### Pending
- [x] Update NPM with the new version. Can you handle it, @sindresorhus? _I don't have permission_
- [ ] Make a Release. I can make it

### CODE REVIEW

**Comment by sindresorhus** [comment]
@UlisesGascon What's your npm username?

**Comment by UlisesGascon** [comment]
@sindresorhus `ulisesgascon` is [my username](https://www.npmjs.com/~ulisesgascon)

**Comment by sindresorhus** [comment]
I've invited you to the npm org. Let me know when you have accepted.

**Comment by UlisesGascon** [comment]
Thanks @sindresorhus! I am part of the org in Npm ;-)

**Comment by sindresorhus** [comment]
Alright, you should have access to publish to npm now.

Use https://github.com/sindresorhus/np to publish (it will generate release notes for you).

**Comment by UlisesGascon** [comment]
@sindresorhus. First time I use NP, I love the idea and the tool ^^. But I have some problems with the Github part in the NP process.  I will investigate what is wrong and I will open a issue/PR for that in NP. 

Captura de pantalla 2019-06-14 a las 12 51 42

I will manually modify the package version and create the ralease in this repo ;-)

**Pull request merged**
