### PR TITLE
Add node 5 to travis config

### PR DESCRIPTION
**Pull request by mischah**
That’s it :octocat:

### CODE REVIEW

**Comment by mischah** [comment]
I changed `5` to `stable` and did a force push :blush:

**Comment by hemanth** [comment]
:+1:

**Comment by ragingwind** [comment]
@mischah Thanks for PR

**Comment by mischah** [comment]
My pleasure :kissing_heart: 

I have to thank you for this generator which helped me to publish my first Chrome Extension:
[Replace “Frameworks” with “Flamewars”](https://chrome.google.com/webstore/detail/replace-%E2%80%9Cframeworks%E2%80%9D-with/dmnlnjijflgoaelbmcgdibcgoniajabm) :joy: 

The next extension will be something more useful and slightly more advanced :octocat:

**Pull request merged**
